// Copyright CSCE 311 Spring 2025
//
// Code generated by ChatGPT in response to assignment prompt.
//
// The Generative AI has produced what is known as a
//   Top-down recursive descent parser
// To be fair, this is overkill for the assignment, but if interested, it is
// parsing a grammer based on the following grammar rules/description:
//
//   Expression -> Term { "+" Term }
//   Term -> Factor { "*" Factor }
//   Factor -> Variable ["'"]
//   Variable -> [a-z]
//

#ifndef UTIL_INCLUDE_BOOL_EXPR_PARSER_H_
#define UTIL_INCLUDE_BOOL_EXPR_PARSER_H_

#include <cstddef>
#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>

//
// Iterate over character array to return a string with all "delims" removed. A
// more correct version would return an std::vector<std::string> to admit to
// the possibility of multi-character tokens, but for our usage this suffices.
//
const std::string Explode(const char input[], char delim = ' ');


//
// Constructs a map from the characters a, b, c, ... x, y, z, one for each
// Boolean value supplied.
//
const std::unordered_map<char, bool> BuildMap(const std::string& boolean_values);


//
// A Boolean expression parser, capable of parsing variables, a-z, ORs +,
// ANDs *, and complemented variables, e.g., a' or z'.
//
class BooleanExpressionParser {
 public:
  BooleanExpressionParser(const std::string& expression,
              const std::unordered_map<char, bool>& values)
    : expression_(expression), values_(values), currentIndex_(0),
      has_error_(0), err_msg_("") {
    // empty
  }

  bool Parse();

  bool HasError() const;

  const std::string Error() const;

 private:
  // Get the current character
  char CurrentChar() const;

  // Advance to the next character
  void Consume();

  // Parse OR ('+') expressions
  bool ParseExpr();

  // Parse AND ('*') expressions
  bool ParseTerm();

  // Parse primary values: variables (a-z), optionally negated with `'`
  bool ParseFactor();

  void ReportError(const std::string& message);


  std::string expression_;
  const std::unordered_map<char, bool>& values_;
  size_t currentIndex_;
  bool has_error_;
  std::string err_msg_;
};


#endif  // UTIL_INCLUDE_BOOL_EXPR_PARSER_H_
